"""empty message

Revision ID: 76bf85bc20e5
Revises: 
Create Date: 2023-09-17 04:00:29.139900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76bf85bc20e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('skin_color', sa.String(length=25), nullable=False),
    sa.Column('hair_color', sa.String(length=20), nullable=False),
    sa.Column('eye_color', sa.String(length=15), nullable=False),
    sa.Column('birth_year', sa.String(length=15), nullable=False),
    sa.Column('gender', sa.String(length=25), nullable=False),
    sa.Column('home_world', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('starships', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('rotation_period', sa.Integer(), nullable=False),
    sa.Column('orbital_period', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=False),
    sa.Column('climate', sa.String(length=30), nullable=False),
    sa.Column('gravity', sa.String(length=10), nullable=False),
    sa.Column('terrain', sa.String(length=30), nullable=False),
    sa.Column('population', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('manufacturer', sa.String(length=90), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('max_atmosphering_speed', sa.String(length=30), nullable=False),
    sa.Column('crew', sa.Integer(), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('starship_class', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('firstname', sa.String(length=50), nullable=False),
    sa.Column('lasttname', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('join_table_people',
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.Column('favorites_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], ),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], )
    )
    op.create_table('join_table_planets',
    sa.Column('planets_id', sa.Integer(), nullable=True),
    sa.Column('favorites_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], ),
    sa.ForeignKeyConstraint(['planets_id'], ['planets.id'], )
    )
    op.create_table('join_table_starships',
    sa.Column('starships_id', sa.Integer(), nullable=True),
    sa.Column('favorites_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], ),
    sa.ForeignKeyConstraint(['starships_id'], ['starships.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('join_table_starships')
    op.drop_table('join_table_planets')
    op.drop_table('join_table_people')
    op.drop_table('favorites')
    op.drop_table('user')
    op.drop_table('starships')
    op.drop_table('planets')
    op.drop_table('people')
    # ### end Alembic commands ###
