"""empty message

Revision ID: fe2b0af1a755
Revises: 76bf85bc20e5
Create Date: 2023-09-17 13:54:23.135053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2b0af1a755'
down_revision = '76bf85bc20e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lastname', sa.String(length=50), nullable=True))
        batch_op.drop_column('lasttname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lasttname', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.drop_column('lastname')

    # ### end Alembic commands ###
